# Generated by Django 5.2.4 on 2025-08-08 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 15, 53, 0, 986957, tzinfo=datetime.timezone.utc)),
        ),
    ]
