# Generated by Django 5.2.4 on 2025-08-08 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_session', '0002_alter_classsession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 15, 54, 10, 855387, tzinfo=datetime.timezone.utc)),
        ),
    ]
