# Generated by Django 5.2.4 on 2025-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_session', '0003_alter_classsession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='duration',
            field=models.PositiveBigIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='classsession',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
