# Generated by Django 5.2.4 on 2025-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'FAIL'), (2, 'PASS'), (4, 'GOOD'), (5, 'EXCELLENT')], null=True),
        ),
    ]
