# Generated by Django 5.2.4 on 2025-08-17 20:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_deadline_assignment_is_published_and_more'),
        ('submission', '0003_submission_marked_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 20, 59, 12, 402453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_submissions', to='assignment.assignment'),
        ),
    ]
