# Generated by Django 5.2.4 on 2025-08-18 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_submission_date_alter_submission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 18, 20, 41, 5, 793811, tzinfo=datetime.timezone.utc)),
        ),
    ]
