# Generated by Django 5.2.4 on 2025-08-22 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_alter_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 12, 17, 15, 968088, tzinfo=datetime.timezone.utc)),
        ),
    ]
